# Uncomment the next line to define a global platform for your project
platform :ios, '14.2'

target 'streamar-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "gRPC-Core", "~> 1.28.2"

  # Pods for streamar-ios
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'Firebase/Storage'
  pod 'FirebaseFirestoreSwift'
  pod 'AzureSpatialAnchors', '~> 2.7.1'

  pod 'Alamofire', '~> 5.2'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxCoreLocation', '~> 1.4'
  pod 'RxDataSources', '~> 4.0'
  pod 'LGButton'
  pod 'MaterialComponents/Buttons'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end