# Uncomment the next line to define a global platform for your project
platform :ios, '13.5'

target 'streamar-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "gRPC-Core", "~> 1.28.2"

  # Pods for streamar-ios
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'Firebase/Storage'
  pod 'AzureSpatialAnchors'

  pod 'iCimulator'
  pod 'Alamofire', '~> 5.2'
end